return {
  "pwntester/octo.nvim",
  cmd = "Octo",
  config = function()
    require("octo").setup({
      pull_requests = {
        order_by = { -- criteria to sort the results of `Octo pr list`
          field = "UPDATED_AT", -- either COMMENTS, CREATED_AT or UPDATED_AT (https://docs.github.com/en/graphql/reference/enums#issueorderfield)
          direction = "DESC", -- either DESC or ASC (https://docs.github.com/en/graphql/reference/enums#orderdirection)
        },
        always_select_remote_on_create = "false", -- always give prompt to select base remote repo when creating PRs
      },
      mappings = {
        issue = {
          -- close_issue = { lhs = "<leader>oic", desc = "close issue" },
          -- reopen_issue = { lhs = "<leader>oio", desc = "reopen issue" },
          -- list_issues = { lhs = "<leader>oil", desc = "list open issues on same repo" },
          -- reload = { lhs = "<C-r>", desc = "reload issue" },
          -- open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
          -- copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
          -- add_assignee = { lhs = "<leader>oiaa", desc = "add assignee" },
          -- remove_assignee = { lhs = "<leader>oiad", desc = "remove assignee" },
          -- create_label = { lhs = "<leader>lc", desc = "create label" },
          -- add_label = { lhs = "<leader>la", desc = "add label" },
          -- remove_label = { lhs = "<leader>ld", desc = "remove label" },
          -- goto_issue = { lhs = "<leader>gi", desc = "navigate to a local repo issue" },
          -- add_comment = { lhs = "<leader>ca", desc = "add comment" },
          -- delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
          -- next_comment = { lhs = "]c", desc = "go to next comment" },
          -- prev_comment = { lhs = "[c", desc = "go to previous comment" },
          -- react_hooray = { lhs = "<leader>oRp", desc = "add/remove 🎉 reaction" },
          -- react_heart = { lhs = "<leader>oRh", desc = "add/remove ❤️ reaction" },
          -- react_eyes = { lhs = "<leader>oRe", desc = "add/remove 👀 reaction" },
          -- react_thumbs_up = { lhs = "<leader>oR+", desc = "add/remove 👍 reaction" },
          -- react_thumbs_down = { lhs = "<leader>oR-", desc = "add/remove 👎 reaction" },
          -- react_rocket = { lhs = "<leader>oRr", desc = "add/remove 🚀 reaction" },
          -- react_laugh = { lhs = "<leader>oRl", desc = "add/remove 😄 reaction" },
          -- react_confused = { lhs = "<leader>oRc", desc = "add/remove 😕 reaction" },
        },
        pull_request = {
          -- checkout_pr = { lhs = "<leader>po", desc = "checkout PR" },
          -- merge_pr = { lhs = "<leader>pm", desc = "merge commit PR" },
          -- squash_and_merge_pr = { lhs = "<leader>psm", desc = "squash and merge PR" },
          -- list_commits = { lhs = "<leader>pc", desc = "list PR commits" },
          -- list_changed_files = { lhs = "<leader>pf", desc = "list PR changed files" },
          -- show_pr_diff = { lhs = "<leader>pd", desc = "show PR diff" },
          -- add_reviewer = { lhs = "<leader>va", desc = "add reviewer" },
          -- remove_reviewer = { lhs = "<leader>vd", desc = "remove reviewer request" },
          -- close_issue = { lhs = "<leader>ic", desc = "close PR" },
          -- reopen_issue = { lhs = "<leader>io", desc = "reopen PR" },
          -- list_issues = { lhs = "<leader>il", desc = "list open issues on same repo" },
          -- reload = { lhs = "<C-r>", desc = "reload PR" },
          -- open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
          -- copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
          -- goto_file = { lhs = "gf", desc = "go to file" },
          -- add_assignee = { lhs = "<leader>opaa", desc = "add assignee" },
          -- remove_assignee = { lhs = "<leader>opad", desc = "remove assignee" },
          -- create_label = { lhs = "<leader>lc", desc = "create label" },
          -- add_label = { lhs = "<leader>la", desc = "add label" },
          -- remove_label = { lhs = "<leader>ld", desc = "remove label" },
          -- goto_issue = { lhs = "<leader>gi", desc = "navigate to a local repo issue" },
          -- add_comment = { lhs = "<leader>ca", desc = "add comment" },
          -- delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
          -- next_comment = { lhs = "]c", desc = "go to next comment" },
          -- prev_comment = { lhs = "[c", desc = "go to previous comment" },
          -- react_hooray = { lhs = "<leader>oRp", desc = "add/remove 🎉 reaction" },
          -- react_heart = { lhs = "<leader>oRh", desc = "add/remove ❤️ reaction" },
          -- react_eyes = { lhs = "<leader>oRe", desc = "add/remove 👀 reaction" },
          -- react_thumbs_up = { lhs = "<leader>oR+", desc = "add/remove 👍 reaction" },
          -- react_thumbs_down = { lhs = "<leader>oR-", desc = "add/remove 👎 reaction" },
          -- react_rocket = { lhs = "<leader>oRr", desc = "add/remove 🚀 reaction" },
          -- react_laugh = { lhs = "<leader>oRl", desc = "add/remove 😄 reaction" },
          -- react_confused = { lhs = "<leader>oRc", desc = "add/remove 😕 reaction" },
        },
        review_thread = {
          -- goto_issue = { lhs = "<leader>gi", desc = "navigate to a local repo issue" },
          -- add_comment = { lhs = "<leader>ca", desc = "add comment" },
          -- add_suggestion = { lhs = "<leader>sa", desc = "add suggestion" },
          -- delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
          -- next_comment = { lhs = "]c", desc = "go to next comment" },
          -- prev_comment = { lhs = "[c", desc = "go to previous comment" },
          -- select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
          -- select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
          -- close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
          -- react_hooray = { lhs = "<leader>oRp", desc = "add/remove 🎉 reaction" },
          -- react_heart = { lhs = "<leader>oRh", desc = "add/remove ❤️ reaction" },
          -- react_eyes = { lhs = "<leader>oRe", desc = "add/remove 👀 reaction" },
          -- react_thumbs_up = { lhs = "<leader>oR+", desc = "add/remove 👍 reaction" },
          -- react_thumbs_down = { lhs = "<leader>oR-", desc = "add/remove 👎 reaction" },
          -- react_rocket = { lhs = "<leader>oRr", desc = "add/remove 🚀 reaction" },
          -- react_laugh = { lhs = "<leader>oRl", desc = "add/remove 😄 reaction" },
          -- react_confused = { lhs = "<leader>oRc", desc = "add/remove 😕 reaction" },
        },
        submit_win = {
          -- approve_review = { lhs = "<C-a>", desc = "approve review" },
          -- comment_review = { lhs = "<C-m>", desc = "comment review" },
          -- request_changes = { lhs = "<C-r>", desc = "request changes review" },
          -- close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
        },
        review_diff = {
          -- add_review_comment = { lhs = "<leader>ca", desc = "add a new review comment" },
          -- add_review_suggestion = { lhs = "<leader>sa", desc = "add a new review suggestion" },
          -- focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
          -- toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
          -- next_thread = { lhs = "]t", desc = "move to next thread" },
          -- prev_thread = { lhs = "[t", desc = "move to previous thread" },
          -- select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
          -- select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
          -- close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
          -- toggle_viewed = { lhs = "<leader><leader>", desc = "toggle viewer viewed state" },
          -- goto_file = { lhs = "gf", desc = "go to file" },
        },
        file_panel = {
          next_entry = { lhs = "j", desc = "move to next changed file" },
          prev_entry = { lhs = "k", desc = "move to previous changed file" },
          select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
          refresh_files = { lhs = "R", desc = "refresh changed files panel" },
          focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
          toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
          select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
          select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
          close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
          toggle_viewed = { lhs = "<leader><leader>", desc = "toggle viewer viewed state" },
        },
      },
    })
  end,
  keys = {
    -- Comment
    { "<leader>oca", "<CMD>Octo comment add<CR>", desc = "󰆃 Add" },
    { "<leader>ocd", "<CMD>Octo comment delete<CR>", desc = "󰆇 Delete" },
    -- Issues
    { "<leader>ois", "<CMD>Octo issue search<CR>", desc = " Search" },
    { "<leader>oib", "<CMD>Octo issue browser<CR>", desc = " Browser" },
    { "<leader>oiu", "<CMD>Octo issue url<CR>", desc = " Url" },
    -- PRs
    { "<leader>opb", "<CMD>Octo pr browser<CR>", desc = " Browser" },
    { "<leader>opc", "<CMD>Octo pr create<CR>", desc = " Create" },
    { "<leader>opd", "<CMD>Octo pr diff<CR>", desc = " Diff" },
    { "<leader>opl", "<CMD>Octo pr list<CR>", desc = " List" },
    { "<leader>opr", "<CMD>Octo pr ready<CR>", desc = " Ready" },
    { "<leader>opu", "<CMD>Octo pr url<CR>", desc = " Url" },
    -- Reviews
    { "<leader>orc", "<CMD>Octo review comments<CR>", desc = " Comments" },
    { "<leader>orC", "<CMD>Octo review commit<CR>", desc = " Commit to review" },
    { "<leader>ord", "<CMD>Octo review discard<CR>", desc = " Discard" },
    { "<leader>ors", "<CMD>Octo review start<CR>", desc = " Start" },
    { "<leader>orr", "<CMD>Octo review resume<CR>", desc = "󰜉 Resume" },
    { "<leader>orp", "<CMD>Octo review submit<CR>", desc = " Push/Submit review" },
    -- Reaction
    { "<leader>oRc", "<CMD>Octo reaction confused<CR>", desc = "󱃟 Confused" },
    { "<leader>oRd", "<CMD>Octo reaction thumbs_down<CR>", desc = " Thumbs down" },
    { "<leader>oRe", "<CMD>Octo reaction eyes<CR>", desc = "󰊪 Eyes" },
    { "<leader>oRh", "<CMD>Octo reaction heart<CR>", desc = " Heart" },
    { "<leader>oRl", "<CMD>Octo reaction laugh<CR>", desc = " Laugh" },
    { "<leader>oRp", "<CMD>Octo reaction party<CR>", desc = "󱁖 Party/Hooray/Tada" },
    { "<leader>oRr", "<CMD>Octo reaction rocket<CR>", desc = " Rocket" },
    { "<leader>oRu", "<CMD>Octo reaction thumbs_up<CR>", desc = " Thumbs up" },
  },
}
