return {
  "pwntester/octo.nvim",
  cmd = "Octo",
  config = true,
  keys = {
    { "<leader>oca", "<CMD>Octo comment add<CR>", desc = "󰆃 Add" },
    { "<leader>ocd", "<CMD>Octo comment delete<CR>", desc = "󰆇 Delete" },
    { "<leader>ois", "<CMD>Octo issue search<CR>", desc = " Search" },
    { "<leader>oib", "<CMD>Octo issue browser<CR>", desc = " Browser" },
    { "<leader>oiu", "<CMD>Octo issue url<CR>", desc = " Url" },
    { "<leader>opb", "<CMD>Octo pr browser<CR>", desc = " Browser" },
    { "<leader>opc", "<CMD>Octo pr create<CR>", desc = " Create" },
    { "<leader>opd", "<CMD>Octo pr diff<CR>", desc = " Diff" },
    { "<leader>opl", "<CMD>Octo pr list<CR>", desc = " List" },
    { "<leader>opr", "<CMD>Octo pr ready<CR>", desc = " Ready" },
    { "<leader>opu", "<CMD>Octo pr url<CR>", desc = " Url" },
    { "<leader>orc", "<CMD>Octo review comments<CR>", desc = " Comments" },
    { "<leader>orC", "<CMD>Octo review commit<CR>", desc = " Commit to review" },
    { "<leader>ord", "<CMD>Octo review discard<CR>", desc = " Discard" },
    { "<leader>ors", "<CMD>Octo review start<CR>", desc = " Start" },
    { "<leader>orr", "<CMD>Octo review resume<CR>", desc = "󰜉 Resume" },
    { "<leader>orp", "<CMD>Octo review submit<CR>", desc = " Push/Submit review" },
    { "<leader>oRc", "<CMD>Octo reaction confused<CR>", desc = "󱃟 Confused" },
    { "<leader>oRd", "<CMD>Octo reaction thumbs_down<CR>", desc = " Thumbs down" },
    { "<leader>oRe", "<CMD>Octo reaction eyes<CR>", desc = "󰊪 Eyes" },
    { "<leader>oRh", "<CMD>Octo reaction heart<CR>", desc = " Heart" },
    { "<leader>oRl", "<CMD>Octo reaction laugh<CR>", desc = " Laugh" },
    { "<leader>oRp", "<CMD>Octo reaction party<CR>", desc = "󱁖 Party/Hooray/Tada" },
    { "<leader>oRr", "<CMD>Octo reaction rocket<CR>", desc = " Rocket" },
    { "<leader>oRu", "<CMD>Octo reaction thumbs_up<CR>", desc = " Thumbs up" },
  },
}
